// departments.ts
export const departments = [
  { serial: 1, value: 'Faculty of Engineering and Technology (FET)' },
  { serial: 2, value: 'Computer Science and Engineering (CSE)' },
  { serial: 3, value: 'Industrial and Production Engineering (IPE)' },
  { serial: 4, value: 'Petroleum and Mining Engineering (PME)' },
  { serial: 5, value: 'Chemical Engineering (ChE)' },
  { serial: 6, value: 'Electrical and Electronic Engineering (EEE)' },
  { serial: 7, value: 'Biomedical Engineering (BME)' },
  { serial: 8, value: 'Textile Engineering (TE)' },
  { serial: 9, value: 'Faculty of Biological Science and Technology (FBST)' },
  { serial: 10, value: 'Microbiology (MB)' },
  { serial: 11, value: 'Fisheries and Marine Bioscience (FMB)' },
  { serial: 12, value: 'Genetic Engineering and Biotechnology (GEBT)' },
  { serial: 13, value: 'Pharmacy (PHAR)' },
  { serial: 14, value: 'Biochemistry and Molecular Biology (BMB)' },
  { serial: 15, value: 'Faculty of Applied Science and Technology (FAST)' },
  { serial: 16, value: 'Environmental Science and Technology (EST)' },
  { serial: 17, value: 'Nutrition and Food Technology (NFT)' },
  { serial: 18, value: 'Food Engineering (FE)' },
  { serial: 19, value: 'Climate and Disaster Management (CDM)' },
  { serial: 20, value: 'Faculty of Health Science (FHS)' },
  { serial: 21, value: 'Physical Education and Sports Science (PESS)' },
  { serial: 22, value: 'Physiotherapy and Rehabilitation (PTR)' },
  { serial: 23, value: 'Nursing and Health Science (NHS)' },
  { serial: 24, value: 'Faculty of Arts and Social Science (FASS)' },
  { serial: 25, value: 'English (ENG)' },
  { serial: 26, value: 'Faculty of Science (FS)' },
  { serial: 27, value: 'Physics (PHY)' },
  { serial: 28, value: 'Chemistry (CHEM)' },
  { serial: 29, value: 'Mathematics (MATH)' },
  { serial: 30, value: 'Applied Statistics and Data Science (ASDS)' },
  { serial: 31, value: 'Faculty of Business Studies (FBS)' },
  { serial: 32, value: 'Accounting and Information Systems (AIS)' },
  { serial: 33, value: 'Management (MGT)' },
  { serial: 34, value: 'Marketing (MKT)' },
  { serial: 35, value: 'Finance and Banking (FB)' },
  { serial: 36, value: 'Faculty of Veterinary Medicine (FVM)' },
  { serial: 37, value: 'Veterinary Medicine (DVM)' },
];

// offices.ts
export const offices = [
  { serial: 1, value: 'Office Of The Vice Chancellor' },
  { serial: 2, value: 'Office Of The Treasurer' },
  { serial: 3, value: 'Office Of The Registrar' },
  { serial: 4, value: 'Public Relation Branch (Registrar Office)' },
  { serial: 5, value: 'Office Of The ICT Cell' },
  { serial: 6, value: 'Office Of The Librarian' },
  { serial: 7, value: 'Office Of The Proctor' },
  { serial: 8, value: 'Office Of The Student Counseling And Guidance' },
  { serial: 9, value: 'Office Of The Director Of Accounts' },
  { serial: 10, value: 'Audit Cell' },
  {
    serial: 11,
    value: 'Office Of The Director Of Planning, Development & Works',
  },
  { serial: 12, value: 'Office Of The Controller Of Examinations' },
  { serial: 13, value: 'Office Of The Chief Engineer' },
  { serial: 14, value: 'Office Of The Chief Medical Officer' },
  { serial: 15, value: 'Office Of The Research Cell' },
  { serial: 16, value: 'Institutional Quality Assurance Cell (IQAC)' },
  { serial: 17, value: 'International Service Center (ISC)' },
  { serial: 18, value: 'Institute For Higher Education and Research (IHER)' },
  {
    serial: 19,
    value:
      'Centre For Sophisticated Instrumentation and Research Laboratory (CSIRL)',
  },
  { serial: 20, value: 'Genome Centre' },
  { serial: 21, value: 'Center for Training and Skill Development (CTSD)' },
  { serial: 22, value: 'Office Of The Physical Education' },
  { serial: 23, value: 'Office Of The Transport Administrator' },
  { serial: 24, value: 'Cyber Centre' },
  { serial: 25, value: 'Teachers and Students Centre (TSC)' },
  { serial: 26, value: 'Shaheed Mashiur Rahman Hall' },
  { serial: 27, value: 'Taposhi Rabeya Hall' },
  { serial: 28, value: 'Munshi Mohammad Meherullah Hall' },
  { serial: 29, value: 'Beerprotik Taramon Bibi Hall' },
  { serial: 30, value: 'Modern Fish Hatchery and Wet Lab' },
];
