export enum Departments {
  // Faculties
  FET = 'Faculty of Engineering and Technology (FET)',
  FBST = 'Faculty of Biological Science and Technology (FBST)',
  FAST = 'Faculty of Applied Science and Technology (FAST)',
  FHS = 'Faculty of Health Science (FHS)',
  FASS = 'Faculty of Arts and Social Science (FASS)',
  FBS = 'Faculty of Business Studies (FBS)',
  FS = 'Faculty of Science (FS)',
  FVM = 'Faculty of Veterinary Medicine (FVM)',

  // Academic Departments
  CSE = 'Computer Science and Engineering (CSE)',
  IPE = 'Industrial and Production Engineering (IPE)',
  PME = 'Petroleum and Mining Engineering (PME)',
  ChE = 'Chemical Engineering (ChE)',
  EEE = 'Electrical and Electronic Engineering (EEE)',
  BME = 'Biomedical Engineering (BME)',
  TE = 'Textile Engineering (TE)',
  MB = 'Microbiology (MB)',
  FMB = 'Fisheries and Marine Bioscience (FMB)',
  GEBT = 'Genetic Engineering and Biotechnology (GEBT)',
  PHAR = 'Pharmacy (PHAR)',
  BMB = 'Biochemistry and Molecular Biology (BMB)',
  EST = 'Environmental Science and Technology (EST)',
  NFT = 'Nutrition and Food Technology (NFT)',
  FE = 'Food Engineering (FE)',
  CDM = 'Climate and Disaster Management (CDM)',
  PESS = 'Physical Education and Sports Science (PESS)',
  PTR = 'Physiotherapy and Rehabilitation (PTR)',
  NHS = 'Nursing and Health Science (NHS)',
  ENG = 'English (ENG)',
  PHY = 'Physics (PHY)',
  CHEM = 'Chemistry (CHEM)',
  MATH = 'Mathematics (MATH)',
  ASDS = 'Applied Statistics and Data Science (ASDS)',
  AIS = 'Accounting and Information Systems (AIS)',
  MGT = 'Management (MGT)',
  MKT = 'Marketing (MKT)',
  FB = 'Finance and Banking (FB)',
  DVM = 'Veterinary Medicine (DVM)',

  // Offices
  VC = 'Office Of The Vice Chancellor',
  TREASURER = 'Office Of The Treasurer',
  REGISTRAR = 'Office Of The Registrar',
  ICT = 'Office Of The ICT Cell',
  LIBRARIAN = 'Office Of The Librarian',
  SMRH = 'Shaheed Mashiur Rahman Hall',
  TRH = 'Taposhi Rabeya Hall',
  MMMH = 'Munshi Mohammad Meherullah Hall',
  BTBH = 'Beerprotik Taramon Bibi Hall',
  PROCTOR = 'Office Of The Proctor',
  COUNSELING = 'Office Of The Student Counseling And Guidance',
  ACCOUNTS = 'Office Of The Director Of Accounts',
  PLANNING = 'Office Of The Director Of Planning, Development & Works',
  CONTROLLER = 'Office Of The Controller Of Examinations',
  ENGINEER = 'Office Of The Chief Engineer',
  MEDICAL = 'Office Of The Chief Medical Officer',
  IHER = 'Institute For Higher Education and Research (IHER)',
  RESEARCH_CELL = 'Office Of The Research Cell',
  IQAC = 'Institutional Quality Assurance Cell (IQAC)',
  CSIRL = 'Centre For Sophisticated Instrumentation and Research Laboratory (CSIRL)',
  GENOME = 'Genome Centre',
  ISC = 'International Service Center (ISC)',
  PE = 'Office Of The Physical Education',
  TRANSPORT = 'Office Of The Transport Administrator',
  AUDIT = 'Audit Cell',
  PR = 'Public Relation Branch (Registrar Office)',
  TSC = 'Teachers and Students Centre (TSC)',
  CYBER = 'Cyber Centre',
  FISH = 'Modern Fish Hatchery and Wet Lab',
  CTSD = 'Center for Training and Skill Development (CTSD)',
}
